# For more info on HTTP files go to https://aka.ms/vs/httpfile
@APIApplication_HostAddress = http://localhost:5116
###Token key
@tocken = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYzYWM4NjNiLWE4YmUtNDEwYi0wOWI4LTA4ZGRkNzIzYTk0MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJzb2tuYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NTUyNTk0MDcsImlzcyI6Ik15Tm90ZXNBcHAiLCJhdWQiOiJNeU5vdGVzQXVkaWVuY2UifQ.z-oTBjQ-UozOLfgWG3fP4mHclxo651MVyuZVsHdTE8J77hOgyb-HZbCLauUr0ghajDzU054DC3M0AKMSNR3gTg

###Get All notes
GET {{APIApplication_HostAddress}}/api/note
Accept: */*
Authorization: {{tocken}}

###Get Note by id
GET {{APIApplication_HostAddress}}/api/note/bb53e3ab-7352-425b-a3a5-a85138b8992a
Accept: */*
Authorization: {{tocken}}

###Create Note
POST {{APIApplication_HostAddress}}/api/note
Accept: */*
Content-Type: application/json
Authorization: {{tocken}}
{
  "title": "New note"
  "content": "New note content"
}

###Update
PUT {{APIApplication_HostAddress}}/api/note/225b033e-3e36-4af7-395a-08ddd723cdd1
Accept: */*
Content-Type: application/json
Authorization: {{tocken}}
{
  "title": "Update note",
  "content": "New note content"
}

###Delete
DELETE {{APIApplication_HostAddress}}/api/note/b6cef7ef-e218-4b1f-395b-08ddd723cdd1
Accept: */*
Authorization: {{tocken}}


###GetAll Users
GET {{APIApplication_HostAddress}}/api/user
Accept: */*
Authorization: {{tocken}}